# action/action.yml
name: 'Generate and Compare Aztec Benchmarks'
description: 'Generates _latest benchmark reports for all contracts using benchmark-cli, then compares them to _base reports and outputs markdown.'
inputs:
  # Inputs for Comparison
  threshold:
    description: 'Regression threshold percentage (e.g., 2.5 for 2.5%). Changes above this are marked red.'
    required: false
    default: '2.5' # Default 2.5%
  output_markdown_path:
    description: 'Path where the comparison markdown report will be saved.'
    required: false
    default: 'benchmark-comparison.md'
outputs:
  comparison_markdown:
    description: "The generated comparison report in Markdown format."
  markdown_file_path:
    description: "The path to the generated markdown file."
runs:
  using: 'node20'
  main: 'index.cjs' # Entry point is within the action directory 
