name: 'Aztec Benchmark Diff'
description: 'Runs Aztec contract benchmarks, saves results, and compares them against a baseline, generating a markdown report.'

outputs:
  report_path:
    description: 'The path to the generated markdown comparison report (determined by Nargo.toml or default).'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'bar-chart-2'
  color: 'blue'
