# .github/workflows/canary.yml
name: Canary Release

on: workflow_dispatch

jobs:
  publish-canary:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Update version
        run: yarn version --new-version "0.0.0-${GITHUB_SHA::8}" --no-git-tag-version

      - name: Build package
        run: yarn build

      - name: Get package version and name
        id: package-info
        run: |
          echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
          echo "name=$(jq -r .name package.json)" >> $GITHUB_OUTPUT

      - name: Publish Canary to npm
        run: npm publish --tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Output Canary Version Info
        run: echo "Published canary version ${{ steps.package-info.outputs.version }} of ${{ steps.package-info.outputs.name }} to npm." 