name: Pre-Release

on:
  pull_request: # TODO: Remove this before pushing to dev branch
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pre-release:
    uses: defi-wonderland/aztec-ci-actions/.github/workflows/pre-release.yml@v0.0.1
    secrets: inherit
